export const RouteConstant = {
  HOME: "/",
  SIGNUP: "/signup",
  LOGIN: "/login",
  LOGIN_RESET_PASSWORD: "login/reset-password-verification",
  LOGIN_FORGOT_PASSWORD: "/forgot-password",
  GUEST_LETTER: "/home/letter-selection",
  GUEST_PACKAGE: "/home/package-selection",
  EMAIL_VERIFICATION: "/mail/account-verification-mail",
  USER: "/user",
  USER_QUOTE: "/user/quote",
  USER_QUOTE_LETTER: "/user/quote/letter",
  USER_QUOTE_PACKAGE: "/user/quote/package",
  USER_SAVED_QUOTE: "/user/saved-quotes",
  USER_SHIPMENT: "/user/shipment",
  USER_SETTING: "/user/setting",
  USER_DELETING_ACCOUNT_VERIFICATION: "/users/delete-verification",
  CHANGE_PASSWORD: "/user/change-password",
  DELETE_USER_ACCOUNT: "/mail/delete-verification-mail",
  CHECKOUT: "/user/quotes/checkout",
  ADMIN: "/admin",
  ADMIN_SAVED_QUOTES: "/admin/saved-quotes",
  ADMIN_ALL_USER: "/admin/all-users",
  ADMIN_UPDATE_USER: "admin/all-users/update",
  ADMIN_REPORT: "/admin/report",
  ADMIN_ALL_SHIPMENT: "/admin/all-shipment",
  ADMIN_SHIPMENT_DETAILS: "/admin/all-shipments/details/:id",
};
